development:
    :adapter: postgres
    :database: cogent_times_development

test: &TEST
    :adapter: postgres
    :database: cogent_times_test

# test: &TEST
#     :adapter: postgres
#     :database: sxh_cogent_times_test
#     :username: build
#     :password: 

production:
    :adapter: postgres
    :database: cogent_times_production
    # username: salary
    # password: salary06
 
 

cucumber:
  <<: *TEST