development:
  adapter: postgres
  database: cogent_times_development

test: &TEST
  adapter: postgres
  database: cogent_times_test

production:
  adapter: postgres
  database: cogent_times_production
  # username: salary
  # password: salary06

cucumber:
  <<: *TEST