development:
    adapter: postgresql
    database: cogent_times_development

test:
    adapter: postgresql
    database: cogent_times_test
  
production:
    adapter: postgresql
    database: cogent_times_production
    # username: salary
    # password: salary06
 
 
